services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql